### ISSUE TITLE
reorderlist

### ISSUE THREAD

**Issue by Ramzankhan123** [nuclearpasta/react-native-drax#100] opened 2021-06-19 11:35 UTC
how reorderlist in nested list
![Simulator Screen Shot - iPhone 11 - 2021-06-19 at 17 07 21](https://user-images.githubusercontent.com/30739629/122641139-f71d8e00-d120-11eb-83de-0ecd2a007588.png)

**Comment by lafiosca** [comment] 2021-06-19 21:04
Could you provide some more detail here? Are you trying to drag items from one DraxList to another?

**Comment by Ramzankhan123** [comment] 2021-06-21 06:14
I have nested array . I want to drag and drop item in one list to another list 

let dummyArray = [
  {
    id: 1,
    text: 'Chloe',
    nestedList: [
      { id: 11, title: 'assignment 1', image: 'https://placekitten.com/200/240', },
      { id: 12, title: 'assignment 2', image: 'https://placekitten.com/200/201', },
      { id: 13, title: 'assignment 3', image: 'https://placekitten.com/200/202', },
      { id: 14, title: 'assignment 4', image: 'https://placekitten.com/200/203', },
    ]
  },
  {
    id: 2,
    text: 'Jasper',
    nestedList: [
      { id: 21, title: 'assignment 11', image: 'https://placekitten.com/200/240', },
      { id: 22, title: 'assignment 12', image: 'https://placekitten.com/200/201', },
      { id: 23, title: 'assignment 13', image: 'https://placekitten.com/200/202', },
      { id: 24, title: 'assignment 14', image: 'https://placekitten.com/200/203', },
    ]
  }
  ]

**Comment by lafiosca** [comment] 2021-06-23 02:23
Sorry, this feature is not currently provided by the library. I'm closing this issue as a duplicate of #71

**Closed by lafiosca** 2021-06-23 02:23 UTC
Labels: DraxList, more information needed, question

**Comment by Ramzankhan123** [comment] 2021-06-27 17:39
I solved my problem with the help of your library.
Thanks for your help

**Comment by vishalparmar22091989** [comment] 2021-09-04 06:22
@Ramzankhan123  Can you give me some idea or code about drag drop  one section item to another section

**Comment by vishalparmar22091989** [comment] 2021-09-04 06:22
@Ramzankhan123  your help save my time

**Comment by vishalparmar22091989** [comment] 2021-09-04 06:25
@lafiosca Yes i am trying follow

trying to drag items from one DraxList to another draglist
