### ISSUE TITLE
Dragging Components on react-native-modal doesn't work.

### ISSUE THREAD

**Issue by OsmonKida** [nuclearpasta/react-native-drax#127] opened 2022-01-11 18:32 UTC
Dragging Components doesn't work on Modal, Is there any updates on this issue https://github.com/nuclearpasta/react-native-drax/issues/69

**Comment by lafiosca** [comment] 2022-01-11 23:08
I'm sorry, there are no updates on that issue. I have not had the time to do any significant research or feature work on this project over the past year, mostly just handling small maintenance items. Contributors are welcome to take a crack at it though.

I'm going to close this issue as a duplicate of #69 though since that one is still open.

**Closed by lafiosca** 2022-01-11 23:08 UTC
Labels: duplicate, research
